repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/golangci/golangci-lint  # golangci-lint hook repo
    rev: v1.42.0  # golangci-lint hook repo revision
    hooks:
    -   id: golangci-lint # hook id
# other hooks: https://github.com/dnephin/pre-commit-golang
